repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
        exclude: ^.idea/
      - id: trailing-whitespace
  - repo: https://github.com/golangci/golangci-lint.git
    rev: v1.59.1
    hooks:
      - id: golangci-lint
        entry: golangci-lint run --fix
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-mod-tidy
