name: pre-commit.ci lite

on:
  push:
    branches:
     - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        # Opposed to `tests.yaml`, we set it to a golangci-lint-compatible version:
        # https://github.com/golangci/golangci-lint/discussions/4830
        go-version: 1.21

    - name: Install dependencies
      run: go mod tidy

    - uses: pre-commit/action@f7acafac0271bdd064cdfa1b13f17b4350e565ed # v3.0.1

    - uses: pre-commit-ci/lite-action@9d882e7a565f7008d4faf128f27d1cb6503d4ebf # v1.0.2
      if: always()
