on:
  push:
    branches:
     - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Read Go version from go.mod
      id: go_version
      run: echo "::set-output name=version::$(grep '^go ' go.mod | awk '{print $2}')"

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ steps.go_version.outputs.version }}

    - name: Install dependencies
      run: go mod tidy

    - uses: pre-commit/action@v3.0.1

    - uses: pre-commit-ci/lite-action@v1.0.2
      if: always()
