on:
  push:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    defaults:
      run:
        shell: ${{ matrix.os == 'windows-latest' && 'pwsh' || '/bin/bash --noprofile --norc -Eeuxo pipefail {0}' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Read Go version from go.mod
        id: go_version
        run: echo "::set-output name=version::$(grep '^go ' go.mod | awk '{print $2}')"

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ steps.go_version.outputs.version }}

      - name: Install dependencies
        run: go mod tidy

      - name: Run tests
        run: go test $(go list ./... | grep -v /junit2html/example) -race -coverprofile=coverage.out

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
